---
abstract: 'Create and manipulate continued fractions'
author:
  - 'John M. Gamble <jgamble@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.4224'
dynamic_config: 0
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-ContinuedFraction
provides:
  Math::ContinuedFraction:
    file: lib/Math/ContinuedFraction.pm
    version: '0.14'
requires:
  Carp: '0'
  Math::BigInt: '1.999816'
  Math::BigRat: '0.2611'
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jgamble/Math-ContinuedFraction.git
version: '0.14'
x_keyword:
  - math
  - continued-fraction
  - sequences
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
